In [5]:
a = 3.4536


print ('%.2f'%a)

3.45


In [6]:
import numpy as np
a = np.linspace(0,5,9)
for i in a :
    k = round(i,2)
    print ('%.2f'%k)


0.00
0.62
1.25
1.88
2.50
3.12
3.75
4.38
5.00


In [7]:
a = np.array([0, 1, 2, 3])
a.shape


(4,)

In [27]:
## import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(input_[2][:3])
#print(input_[1:4][3])
print(input_[2:4][:])
print(input_[1:3,1:3])

[11 12 13]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


In [34]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
a = print(input_[2,:3])
b = print(input_[1:4,3])
c = print(input_[2:4,:])
d = print(input_[1:3,1:3])
for i in range(3) :
    print(a[i],end=' ')
print()    
for i in  range(3):
    print(b[i],end=' ')  
print()     
for i in range(2) :
    for j in range(5) :
      print(c[i][j],end=' ')
print()     
for i in range(2) :
    for j in range(2):
      print(d[i][j],end=' ') 
print()     

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


TypeError: 'NoneType' object is not subscriptable

In [38]:
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
a = print(input_[2,:3])
b = print(input_[1:4,3])
c = print(input_[2:4,:])
d = print(input_[1:3,1:3])
print(*a, sep = " ")
print(*b, sep = " ")
print(*c, sep = " ")
print(*d, sep = " ")

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


TypeError: print() argument after * must be an iterable, not NoneType

In [39]:
a_list = ["a", "b", "c"]

print(*a_list, sep = ", ")

a, b, c
