In [2]:

import numpy as np
from sklearn import preprocessing
from sklearn import model_selection

In [3]:
data = np.loadtxt("0000000000002419_training_ccpp_x_y_train (1).csv", delimiter=",")

In [25]:
testing_data = np.loadtxt("0000000000002419_test_ccpp_x_test (1).csv",delimiter=",")

In [5]:
def cost(m, x, y):
    cost=0
    for i in range(len(x)):
        cost+=(1/len(x))*((y[i]-sum(m*x[i]))**2)
    print(cost)

In [6]:
def step_gradient(X, Y, m, alpha):
    m_slope=np.zeros(len(X[0]))
    for i in range(len(X)):
        x=X[i]
        y=Y[i]
        for j in range(len(x)):
            m_slope[j]+=(-2/len(X))*(y-sum(m*x))*x[j]
    new_m=m-(alpha*m_slope)
    return new_m

In [7]:
def gd(x, y, alpha, iterations):
    m=np.zeros(len(x[0]))
    for i in range(iterations):
        m=step_gradient(x, y, m,alpha)
    return m



In [8]:
def gradient_descent(x, y):
    iterations=200
    alpha=0.1
    x=np.append(x, np.ones(len(x)).reshape(-1, 1), axis=1)# for the intercept coloumn
    m=gd(x, y, alpha, iterations)
    return m

In [9]:
x=data[:, :-1]

In [10]:
x

array([[   8.58,   38.38, 1021.03,   84.37],
       [  21.79,   58.2 , 1017.21,   66.74],
       [  16.64,   48.92, 1011.55,   78.76],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74],
       [  16.37,   54.3 , 1017.94,   63.63],
       [  30.11,   62.04, 1010.69,   47.96]])

In [11]:
y=data[:, -1]

In [12]:
y

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [13]:
c_coloumn = np.ones((len(testing_data),1))
testing_data =np.append(testing_data,c_coloumn,axis =1 )#adding coloumn for the intercept
testing_data.shape

(2392, 5)

In [17]:
x.shape

(7176, 4)

In [ ]:
sq=[]
for i in range(len(x[0])):
    for j in range(i, len(x[0])):
        sq.append(x[:, i]*x[:, j])
sq=np.array(sq)
for i in sq:
    x=np.append(x, i.reshape(-1, 1), axis=1)

In [21]:
scaler=preprocessing.StandardScaler()
scaler.fit(x)
x=scaler.transform(x)
m=gradient_descent(x, y)

In [16]:
m.shape

(5,)

In [22]:
m

array([-1.47722756e+01, -2.99083025e+00,  3.74019566e-01, -2.29976796e+00,
        4.54431293e+02])

In [24]:
testing_data.shape

(2392, 5)

In [26]:
testing_data1 = scaler.transform(testing_data)

In [28]:
x_test=np.append(testing_data1, np.ones(len(testing_data1)).reshape(-1, 1), axis=1)

In [29]:




ans=[]
for i in x_test:
    ans.append(sum(i*m))
for i in ans:
    print(i)
ans=np.array(ans)
np.savetxt(X=ans,fname='predictions4.csv' , delimiter=',', fmt='%.5f')

323.7669242669395
352.6900117701189
27.12035902261863
265.54174596772157
315.24420025486825
163.80748085245597
388.17867176649264
125.1204261108108
424.48393374770524
92.99999676060492
53.29925231069245
3.030739743080801
365.94809782219306
283.28357558338854
139.80734793904674
227.4100074415783
483.04837717100395
157.56920290604847
-23.51885718203954
110.81875849016404
70.92270048743467
421.6619119343539
235.45725216791976
369.0189372746949
17.63153673939712
64.01482744030812
301.03974341102816
328.84615431876574
58.63555282534111
379.72088147661384
115.49484408004167
30.812003565303314
155.0077186269089
332.0038756760271
322.3030996266209
334.3899938611045
154.33591722631928
222.3141809130238
115.2854705713741
411.06514506990067
310.8676891134445
12.50010182572504
354.9537339082881
295.3218929918667
280.38001873490305
486.84668475187686
70.8309390845609
5.107849593727963
83.74387632386163
357.2845020892106
341.9364225606874
292.90897585612674
350.7575059962708
69.71864822938414
295.75

2.321481564642852
430.08477584312686
155.25649008922147
285.3305239817117
222.15981241359137
377.97967933637597
420.0504550832842
427.1377590539519
313.96835584138864
341.8136086903102
61.926464060713386
155.1402424621645
-10.57292699905247
167.45925926167757
17.64932525620935
351.98206006307566
393.1659865568622
406.20730606668417
294.3850229620232
263.6028551129229
390.10765920967015
203.22042901146426
38.9863374490796
310.4361120124069
375.20478593078036
94.2882588320503
287.9589112104134
285.2434010184613
16.458535791016516
56.725413370614774
143.37011672905516
13.542713718136326
223.69412397815265
428.0576211606342
294.2643044139279
326.96801961737026
334.45042919946604
283.9564072727853
3.951564572431778
110.34992400519201
188.12188581839212
52.001925199797654
201.36781748329673
74.7803048932571
386.3346349381833
67.18533043832139
330.805549369869
329.526244442961
311.57676721745156
174.55017111770655
339.36711330803473
336.1719320768565
173.0341126844159
48.4375912086403
58.2270

In [99]:
 \